name: Automate Infrastructure Teardown

# This tells GitHub to run this pipeline ONLY when new code is pushed to the main branch
on:
  push:
    branches:
      - main

jobs:
  delete-cloudformation:
    runs-on: ubuntu-latest # This is the virtual machine GitHub provides for free
    
    steps:
      # Step 1: The virtual machine downloads your repository code
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      # Step 2: We use an official AWS tool to securely log into your account using your hidden secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Step 3: The pipeline runs the deletion command automatically
      - name: Delete CloudFormation Stack
        run: |
          aws cloudformation delete-stack --stack-name automated-cicd-stack
